### ISSUE TITLE
fix browser client request fallback to the origin server on error

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/browser-client#24]
code metaplex wrote to reproduce the problem:
```js
  useEffect(() => {
    const runEffect = async () => {
      const response = await fetch(
        'https://djib.io/ipfs/QmeXKfBnypgzpnEW2YkXZhbWxN5zB38saW6rvdxiS2k88f'
      );
      const data = await response.json();
      return data;
    };

    runEffect().then(console.log).catch(console.error);
  }, []);
```

related screenshots metaplex captured

![Image](https://github.com/filecoin-saturn/browser-client/assets/1041265/77233342-c67e-49f5-ad7b-ceb1ed5f943e)
![Image](https://github.com/filecoin-saturn/browser-client/assets/1041265/b05b834d-84fe-4798-8168-b85c37982eb3)
![Image](https://github.com/filecoin-saturn/browser-client/assets/1041265/1a6dfaa0-40b2-41df-8d7d-1baf0e9e5eeb)

**Comment by AmeanAsad** [comment]
## Update:
- PR for this issued: https://github.com/filecoin-saturn/js-client/pull/37.

- from local testing, the fallback without hitting the origin was able to retrieve the CID. Either case, now there is an option to inject an origin into requests which gets hits if all else fails.

**Comment by wilkyr31d** [comment]
@AmeanAsad can this be resolved?

**Comment by AmeanAsad** [comment]
@wilkyr31d This was resolved last week.
- JS client was released: https://github.com/filecoin-saturn/js-client/commit/9217c166b79f66c454ca4a9f498f6541742a75d7
- Browser client also updated: https://github.com/filecoin-saturn/browser-client/pull/23
