### ISSUE TITLE
improve CID detection in URLs -> detect cids when delimited by percent encodings

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/browser-client#30]
cids in urls that get encoded into other urls fail to be detected. for example this url:

  * https://proxy.com/?url=ipfs.io%2Fipfs%2Fbafybeidrf56yzbkocajbloyafrebrdzsam3uj35sce2fdyo4elb6zzoily

will fail because the percent encoded `%2F` token, a percent encoded `/`, breaks cid detection. this is a common occurrence for gateways and other reverse proxy urls, where the url which contains the cid to be accelerated gets percent encoded as a url parameter

a simple pseudocode algorithm to fix:
1. check for percent encoded tokens in the url
2. if percent encoded tokens detected, percent decode the url
3. check again for cids and then verify that any cid found exists in its entirety in the original url, too. ie verify that cid didnt pop into existence due to url decoding
4. if found and passes the above verification -> boom, cid found and accelerate that cid 👏 

a fancier algorithm could check for multiple levels of percent encoding. like a url with cid in it twice encoded. but for now? overkill. lets just do something simple that works now and ship it imo

another fancier algorithm could be iterate through all url params and path tokens, percent decode them, and look for cids in each those. that would also work, be 'cleaner', and be robust

**Comment by wilkyr31d** [comment]
in PR
